### ISSUE TITLE
input type number not found

### ISSUE THREAD

**Issue by mo20130123** [GeneaLabs/laravel-casts#42]
input type number should be exist as well as input type radio

**Comment by mikebronner** [comment]
Thanks for the report, @mo20130123. `@radio` does exist, can you give me an example that doesn't work? I'll add `@number` soon, noticed that missing as well. I think I removed it because of some issues a while back under different browsers.

**Comment by mo20130123** [comment]
i used it like this @radio('gender',null,['label' => 'Profile image'])
and it doesn't work 
@mikebronner btw now i use this plugin as my daily driver and i recommend it to my friends

**Comment by mikebronner** [comment]
Thanks! I am working on buttoning up and cleaning code this weekend, adding more unit tests, etc, to make it more stable. i will follow up with radio button and number field for you tomorrow, and will try to get them both implemented correctly and working. Thanks again for reporting that.

**Comment by mikebronner** [comment]
@mo20130123 just checked the code ... radio button works like the checkbox:

`@radio (string $fieldName, string $value, bool $isChecked, array $options = [])`

Let me know if that doesn't work. It's been in the code that way, and I verified it with a unit test). I will have number field added in a little bit.

**Comment by mikebronner** [comment]
This has been added to release 0.6.5, coming in a few minutes.
